//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int Articulo_Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int Categoria_Id { get; set; }
        public int Marca_Id { get; set; }
        public int Proveedor_Id { get; set; }
        public int Unidad_Id { get; set; }
        public int Color_Id { get; set; }
        public Nullable<double> Alto { get; set; }
        public Nullable<double> Ancho { get; set; }
        public string Gtin { get; set; }
        public Nullable<decimal> Ultimo_Costo { get; set; }
        public string Usuario_Crea { get; set; }
        public string Usuario_Modifica { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public Nullable<System.DateTime> Fecha_Modificacion { get; set; }
        public Nullable<int> Estado_Id { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Color Color { get; set; }
        public virtual Estado Estado1 { get; set; }
        public virtual Marcas Marcas { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual UnidadMedida UnidadMedida { get; set; }
    }
}
