//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oficina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oficina()
        {
            this.Autorizador = new HashSet<Autorizador>();
            this.OrdenCompraEncabezado = new HashSet<OrdenCompraEncabezado>();
        }
    
        public int Oficina_Id { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string RazonSocial { get; set; }
        public string Direccion { get; set; }
        public string Ruc { get; set; }
        public string Telefono { get; set; }
        public string Representante { get; set; }
        public Nullable<bool> ImagenLogo { get; set; }
        public Nullable<int> ConsecutivoOrdenCompra { get; set; }
        public Nullable<int> Estado_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorizador> Autorizador { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraEncabezado> OrdenCompraEncabezado { get; set; }
    }
}
