//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompraEncabezado
    {
        public int NOrden { get; set; }
        public int Autorizador_Id { get; set; }
        public int Oficina_Id { get; set; }
        public int Proveedor_Id { get; set; }
        public int Moneda_Id { get; set; }
        public int ModoPago_Id { get; set; }
        public string DireccionEntrega { get; set; }
        public string Referencia { get; set; }
        public string Credito { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal Iva { get; set; }
        public decimal Total { get; set; }
        public int EstadoOrden_Id { get; set; }
        public string Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public System.DateTime FechaPago { get; set; }
        public Nullable<int> CategoriaOrden_Id { get; set; }
        public Nullable<decimal> PagoCajaChica { get; set; }
        public string ElaborarCheque { get; set; }
    
        public virtual Categoria_OCompra Categoria_OCompra { get; set; }
        public virtual EstadoOrden EstadoOrden { get; set; }
        public virtual ModoPago ModoPago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Oficina Oficina { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
