//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Articulo = new HashSet<Articulo>();
            this.OrdenCompraEncabezado = new HashSet<OrdenCompraEncabezado>();
        }
    
        public int Proveedor_Id { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public string Contacto { get; set; }
        public Nullable<int> Pais_Id { get; set; }
        public string NombreRepresentante { get; set; }
        public string CargoRepresentante { get; set; }
        public string NumeroRuc { get; set; }
        public string Direccion { get; set; }
        public string Correo { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public decimal MontoCredito { get; set; }
        public decimal Saldo { get; set; }
        public Nullable<int> DiasPagoFacturaDefault { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<int> Estado_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulo { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenCompraEncabezado> OrdenCompraEncabezado { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
