//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SISCOMPEntities : DbContext
    {
        public SISCOMPEntities()
            : base("name=SISCOMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Articulo> Articulo { get; set; }
        public virtual DbSet<Autorizador> Autorizador { get; set; }
        public virtual DbSet<Categoria_Articulo> Categoria_Articulo { get; set; }
        public virtual DbSet<Categoria_OCompra> Categoria_OCompra { get; set; }
        public virtual DbSet<Color> Color { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<EstadoOrden> EstadoOrden { get; set; }
        public virtual DbSet<Marcas> Marcas { get; set; }
        public virtual DbSet<ModoPago> ModoPago { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<OrdenCompraEncabezado> OrdenCompraEncabezado { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposCambio> TiposCambio { get; set; }
        public virtual DbSet<UnidadMedida> UnidadMedida { get; set; }
        public virtual DbSet<OrdenCompraDetalle> OrdenCompraDetalle { get; set; }
    }
}
