//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposCambio
    {
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Oficial { get; set; }
    }
}
