//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignatura
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public double NotaMinRegular { get; set; }
        public double NotaMinExtraDerecho { get; set; }
        public double NotaMaxExtraDerecho { get; set; }
        public double NotaMinConvalidacion { get; set; }
        public double NotaMinSuficiencia { get; set; }
        public double NotaMinTutoria { get; set; }
        public System.DateTime FechaModifica { get; set; }
        public string UsuarioModifica { get; set; }
        public bool Estado { get; set; }
        public string Identificador { get; set; }
    }
}
