//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocenteAsignatura
    {
        public int Id { get; set; }
        public double RecintoId { get; set; }
        public double DocenteId { get; set; }
        public double AsignaturaId { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
