//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackSys.Models.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public int Id { get; set; }
        public int RecintoId { get; set; }
        public Nullable<int> ProfesionId { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<int> CargoActualId { get; set; }
        public Nullable<int> TipoDocumentoId { get; set; }
        public string Cedula_Documento { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> FechaNac { get; set; }
        public Nullable<int> EtniaId { get; set; }
        public Nullable<int> PaisId { get; set; }
        public string DominaIdiomas { get; set; }
        public string NombreIdioma { get; set; }
        public string NivelAlcanzado { get; set; }
        public Nullable<int> DepartamentoId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public string Zona { get; set; }
        public string EstadoCivil { get; set; }
        public Nullable<int> NHijos { get; set; }
        public string Discapacidad { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> EjercicioDirectivoId { get; set; }
        public Nullable<int> MaximoNivelFpId { get; set; }
        public string NombreTitulos { get; set; }
        public string TieneFormacionPedagogica { get; set; }
        public string NombreFormacionPedagogica { get; set; }
        public Nullable<int> AnioFormacionPedadogica { get; set; }
        public Nullable<int> TipoContratoId { get; set; }
        public Nullable<int> CategoriaDocenteId { get; set; }
        public Nullable<int> AnosAntiguedad { get; set; }
        public string PservUNICAM { get; set; }
        public string PServ_UALN { get; set; }
        public string PServ_RSJ { get; set; }
        public string PServ_Prepa { get; set; }
        public Nullable<int> NoGrupos { get; set; }
        public Nullable<int> NoAsignaturas { get; set; }
        public string NoAsigMod { get; set; }
        public string RealizaInvestigacion { get; set; }
        public Nullable<int> DocenteAreaInvestigacionId { get; set; }
        public string Tutorias { get; set; }
        public Nullable<int> NoMTGrado { get; set; }
        public Nullable<int> NoFTGrado { get; set; }
        public Nullable<int> NoMTPosgrado { get; set; }
        public Nullable<int> NoFTPosgrado { get; set; }
        public string Estudia { get; set; }
        public Nullable<int> NivelFpEstudios { get; set; }
        public string NombreEstudios { get; set; }
        public string BecaEstudios { get; set; }
        public string ProcedBeca { get; set; }
        public string TipoBeca { get; set; }
        public Nullable<decimal> MontoBeca { get; set; }
        public string Capacitaciones { get; set; }
        public Nullable<int> AreaCapacitacionId { get; set; }
        public Nullable<int> HorasClase { get; set; }
        public string NoInss { get; set; }
        public Nullable<int> HorasClaseSemana { get; set; }
        public Nullable<decimal> ValorXHoraClase { get; set; }
        public string UsuarioModifica { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaModifica { get; set; }
        public bool Activo { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Recinto Recinto { get; set; }
        public virtual Municipio Municipio { get; set; }
        public virtual Profesion Profesion { get; set; }
        public virtual TipoContrato TipoContrato { get; set; }
    }
}
